# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_d901fd6725715e7af98283b75caff589e55d98c0

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

# Analysis settings
sonar.sources=client,controllers,helpers,middlewares,tests
sonar.tests=client,controllers,helpers,middlewares,tests

# Coverage report path
sonar.javascript.lcov.reportPaths=coverage/backend/lcov.info,coverage/frontend/lcov.info

# Exclusions
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**


# Mark tests as tests if you want clearer organization
sonar.test.inclusions=**/*.test.js,**/*.spec.js,**/*.test.ts,**/*.spec.ts,**/*.test.tsx,**/*.spec.tsx